# Generated by Django 6.0.4 on 2026-09-30 17:00

from django.conf import settings
from django.db import migrations, models


def invalidate_legacy_otps(apps, schema_editor):
    profile = apps.get_model('ErrandM8App', 'Profile')
    profile.objects.exclude(otp_code='').update(otp_code='', otp_attempts=0)


class Migration(migrations.Migration):

    dependencies = [
        ('ErrandM8App', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(invalidate_legacy_otps, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='profile',
            name='otp_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'category'], name='task_pending_category_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'pickup_latitude', 'pickup_longitude'], name='task_nearby_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['client', '-created_at'], name='task_client_recent_idx'),
        ),
    ]
