# Generated by Django 6.0.4 on 2026-04-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErrandM8App', '0018_profile_is_online_profile_jobs_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('price_proposed', 'Concierge proposed a price'), ('price_countered', 'Counter-offer received'), ('task_accepted', 'Errand accepted'), ('task_declined', 'Errand declined'), ('task_completed', 'Errand completed'), ('payment_received', 'Payment received'), ('review_received', 'Review received'), ('chat_message', 'New message'), ('otp', 'OTP sent')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('concierge', 'Concierge')], default='client', max_length=10),
        ),
    ]
